### ISSUE TITLE
Check-list for 0.5.0 final

### ISSUE THREAD

**Issue by sjrd** [scala-js/scala-js-website#42]
- [x] Publish Scala.js 0.5.0 on Bintray
- [x] Bump DOM to 0.6 and make it use Scala.js 0.5.0
  - [x] Publish on Bintray
- [x] Add `jsDependencies` to jQuery (scala-js/scala-js-jquery#7) and bump to 0.6, + make it use Scala.js 0.5.0
  - [x] Publish it on Bintray
- [x] Publish pickling 0.3.1 for 0.5.0
- [x] Publish scala-parser-combinators 1.0.1 for Scala.js 0.5.0
- [x] Merge #38
- [x] Publish APIs for 0.5.0 on the website
- [x] Publish CLI on website
- [x] Release notes, aka #43
- [x] Big "Current release" on the front page (possibly in #38)
